Repository sarthakroy2002/Scripts, pull requests merged in 2022-10, with the labels that each got.

#2 scripts: Add Jadx installation script
  personal/install_jadx.sh
Labels: hacktoberfest-accepted, hacktoberfest

#3 C3_build_script: Adapt for new neutron-clang release approach
  Kernel/C3_build_script.sh
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#4 AOSP: Use $SOURCEDIR instead
  AOSP/aosp-13.sh
  AOSP/arrow-RMX2020.sh
  AOSP/cipher-RMX2020.sh
  AOSP/lineage-RMX2020.sh
  AOSP/twrp-build.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#5 scripts: Reformat with shfmt
  AOSP/aosp-13.sh
  AOSP/cipher-RMX2020.sh
  AOSP/lineage-RMX2020.sh
  AOSP/twrp-build.sh
  Kernel/C3_build_script.sh
  Kernel/C3_eva_kernel.sh
  Kernel/C3_standalonescript.sh
  commit-msg
  personal/ubuntu_envsetup.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#7 scripts: add AtomX kernel script
  AtomX.sh
Labels: hacktoberfest-accepted, hacktoberfest

#8 Scripts:Added Zram installation in script
  personal/ubuntu_envsetup.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#9 scripts: Fix/Add shebangs
  AOSP/aosp-building.sh
  Kernel/C3_eva_kernel.sh
  Kernel/C3_standalonescript.sh
  personal/install_jadx.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#11 scripts: Add rom build script
  AOSP/rom.sh
Labels: hacktoberfest-accepted, hacktoberfest

#13 scripts: Add missing non-quoted backslash
  Kernel/C3_build_script.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#14 Improve the TWRP Building script
  AOSP/twrp-build.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#15 scripts: Use logical-OR operator for condition of REPO_URL evaluation
  Kernel/C3_build_script.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#16 scripts: Avoid regenerating defconfig multiple times
  Kernel/C3_build_script.sh
  Kernel/C3_eva_kernel.sh
  Kernel/C3_standalonescript.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#20 Update for lineage-20.0
  AOSP/lineage-RMX2020.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#22 scripts : setting up arch for building
  personal/arch_envsetup.sh
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#23 scripts: Add script for building kernel
  Kernel/C3_CI_script.sh
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#24 scripts : setting up sshid
  personal/arch_envsetup.sh
  personal/sshid_setup.sh
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#25 scripts: package manager check and run setup accordingly
  personal/setup.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#26 scripts : added support for ubuntu
  personal/sshid_setup.sh
  personal/ubuntu_envsetup.sh
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#28 add script for PixelOS mojito
  AOSP/pixelos-mojito.sh
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#31 Create install_android_sdk.sh
  personal/install_android_sdk.sh
Labels: hacktoberfest-accepted, hacktoberfest

#30 Create fedora.sh
  personal/fedora.sh
Labels: hacktoberfest-accepted, hacktoberfest

#29 Create android_build_env.sh
  android_build_env.sh
Labels: hacktoberfest-accepted, hacktoberfest

#32 Create cache.sh
  cache.sh
Labels: hacktoberfest-accepted, hacktoberfest

#33 Fix error Sticker post and Fix LLVM builds
  Kernel/C3_build_script.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#35 Scripts: Add twrp building script for G
  AOSP/twrp-build-G.sh
Labels: hacktoberfest-accepted, hacktoberfest

#34 sync needed prebuilts
  AOSP/pixelos-mojito.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#36 One stop solution for preparing your mac for Dev
  One-click_setup_for_Mac_Devs.sh
Labels: hacktoberfest-accepted, hacktoberfest

#37 Add Script for Project 404 X00T
  AOSP/404-X00T.sh
Labels: hacktoberfest-accepted, hacktoberfest

#38 Add Kernel Compilation Script for X00T
  Kernel/X00T_trb_kernel.sh
Labels: hacktoberfest-accepted, hacktoberfest

#39 kernel: add clang 9 build script
  Kernel/kernel-clang9-build.sh
Labels: hacktoberfest-accepted, hacktoberfest

#41 Add script to setup build environment on Gentoo
  personal/gentoo.sh
Labels: hacktoberfest-accepted, hacktoberfest

#42 AOSP: Add PixelOS RMX2020 Build Script
  AOSP/pixelos-RMX2020.sh
Labels: hacktoberfest-accepted, hacktoberfest

#43 Add Android Open Source Project sync script
  AOSP/AOSP-sync.py
Labels: hacktoberfest-accepted, hacktoberfest

#45 scripts: add Kernel Script for r5x with Proton Clang.
  Kernel/r5x-proton-blush.sh
Labels: hacktoberfest-accepted, hacktoberfest

#46 Add script for PixelExperience-RMX1941
  AOSP Scripts/aosp-RMX1941.sh
Labels: hacktoberfest-accepted, hacktoberfest

#47 scripts: Ask for Branch to Sync.
  AOSP Scripts/AOSP-sync.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#48 Add script for CipherOS-RM6785
  AOSP Scripts/cipher-RM6785.sh
Labels: hacktoberfest-accepted, hacktoberfest

#49 Init. script for miatoll devices.
  AOSP Scripts/Pixelexperience-miatoll.sh
Labels: hacktoberfest-accepted, hacktoberfest

#50 kernel scripts: Add script to merge CLO tag
  Kernel Scripts/merge_clo_tag.sh
Labels: hacktoberfest-accepted, hacktoberfest

#51 AOSP: add lineage m20lte building script
  AOSP Scripts/lineage-m20lte.sh
Labels: hacktoberfest-accepted, hacktoberfest

#52 Added script to setup nipe
  Installation Scripts/nipeTorGateway.sh
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#53 Updated to Switch case statement & fixed some stuff.
  AOSP Scripts/Pixelexperience-miatoll.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#54 AOSP: Script to build Corvus for Realme 5 Series
  AOSP Scripts/corvus-r5x.sh
Labels: hacktoberfest-accepted, hacktoberfest

#55 corvus_r5x-script: Use "depth=1" For Repo Init And Sync
  AOSP Scripts/corvus-r5x.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#56 corvus_r5x-script: Use Brightness Curve Patch From ArrowOS
  AOSP Scripts/corvus-r5x.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#58 Refractor fedora setup script
  Installation Scripts/fedora.sh
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#59 Add apktool install script
  Installation Scripts/install_apktool.sh
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#61 AOSP Script:Custom Build Script for Realme 2 Pro
  AOSP Scripts/RMX1801_build_script.sh
Labels: hacktoberfest-accepted, hacktoberfest

#62 Enhanced the build source
  AOSP Scripts/Pixelexperience-miatoll.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#63 Script to download rom sources
  AOSP Scripts/universal_aosp.sh
Labels: hacktoberfest-accepted, hacktoberfest

#67 Made necessary changes :-
  AOSP Scripts/awaken-r5x.sh
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest
