Repository sarthakroy2002/Scripts, pull requests merged in 2023-10, with the labels that each got.

#71 Improve script for gentoo
  Installation Scripts/gentoo.sh
Labels: enhancement, hacktoberfest-accepted

#72 AOSP: sync: Convert into bash script
  AOSP Scripts/AOSP-sync.py
  AOSP Scripts/AOSP-sync.sh
Labels: enhancement, hacktoberfest-accepted

#74 scripts: Maintain consistent formatting across all scripts
  AOSP/arrow-mojito.sh
  AOSP/generic-rom.sh
  AOSP/twrp-build.sh
  Kernel/AtomX-Build-Script.sh
  Kernel/C3_CI_script.sh
  Kernel/C3_build_script.sh
  Kernel/C3_eva_kernel.sh
  Kernel/C3_standalone-script.sh
  Kernel/X00T_trb_kernel.sh
  Kernel/clang9-kernel-build.sh
  Kernel/merge_clo_tag.sh
  Kernel/r5x-proton-blush-build.sh
  Kernel/wasabi_build_script.sh
  Setup/One-click_setup_for_Mac_Devs.sh
  Setup/android_build_env.sh
  Setup/arch_envsetup.sh
  Setup/arch_post_setup.sh
  Setup/cache.sh
  Setup/fedora.sh
  Setup/install_android_sdk.sh
  Setup/nipeTorGateway.sh
  Setup/sshid_setup.sh
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#75 scripts: Add script for alpine linux distro
  Setup/alpine_setup.sh
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#76 kernel: Initial build script for r5x-Graveyard
  Kernel/r5x-Graveyard_build-script.sh
Labels: hacktoberfest-accepted

#82 setup.sh : Optimize and fix a typo
  Setup/setup.sh
Labels: hacktoberfest-accepted

#84 setup.sh: Add Support for Fedora based linux distro's
  Setup/fedora_envsetup.sh
  Setup/setup.sh
Labels: hacktoberfest-accepted

#85 Shell: Script to enable zram
  Setup/zram-setup.sh
Labels: hacktoberfest-accepted
